[package]
name = "rcode"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
dotenvy = "0.15.7"
openai_api_rust = "0.1.9"
ratatui = "0.30.0"
ratatui-textarea = "0.9.1"
rig-core = "0.35.0"
textwrap = "0.16.2"
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
tui-scrollview = "0.6.4"
